// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Connect() {
    return $Call.ByID(1262535069);
}

/**
 * @param {string} id
 * @param {string} firstMessage
 * @returns {$CancellablePromise<void>}
 */
export function CreateLocalConversation(id, firstMessage) {
    return $Call.ByID(863391147, id, firstMessage);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLocalConversation(id) {
    return $Call.ByID(2155173110, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(3974687647);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GenerateConversationId() {
    return $Call.ByID(2266856264);
}

/**
 * @returns {$CancellablePromise<models$0.LocalConversation[]>}
 */
export function GetLocalConversations() {
    return $Call.ByID(3614855678).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} conversationId
 * @returns {$CancellablePromise<models$0.LocalMessage[]>}
 */
export function GetLocalMessages(conversationId) {
    return $Call.ByID(2192898454, conversationId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConnected() {
    return $Call.ByID(3039307876);
}

/**
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameConversation(id, name) {
    return $Call.ByID(3701426952, id, name);
}

/**
 * @param {string} errorMessage
 * @param {string} conversationId
 * @returns {$CancellablePromise<void>}
 */
export function ReportError(errorMessage, conversationId) {
    return $Call.ByID(3174020663, errorMessage, conversationId);
}

/**
 * @param {string} conversationId
 * @param {string} role
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveLocalMessage(conversationId, role, content) {
    return $Call.ByID(1089126342, conversationId, role, content);
}

/**
 * @param {string} conversationId
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(conversationId, message) {
    return $Call.ByID(3702379410, conversationId, message);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(2559786954, app);
}

/**
 * @param {string} notice
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDeviceNotice(notice) {
    return $Call.ByID(3669840130, notice);
}

// Private type creation functions
const $$createType0 = models$0.LocalConversation.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.LocalMessage.createFrom;
const $$createType3 = $Create.Array($$createType2);
