// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @returns {$CancellablePromise<models$0.UpdateCheckResult | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(4135676840).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentVersion() {
    return $Call.ByID(1795688449);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetNotice() {
    return $Call.ByID(4281164598);
}

// Private type creation functions
const $$createType0 = models$0.UpdateCheckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
