// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @param {string} isoTime
 * @returns {$CancellablePromise<string>}
 */
export function FormatResetTime(isoTime) {
    return $Call.ByID(3006650039, isoTime);
}

/**
 * @returns {$CancellablePromise<models$0.UsageStatus | null>}
 */
export function GetUsageStatus() {
    return $Call.ByID(4184407689).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.UsageStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
