// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LocalConversation {
    /**
     * Creates a new LocalConversation instance.
     * @param {Partial<LocalConversation>} [$$source = {}] - The source object to create the LocalConversation.
     */
    constructor($$source = {}) {
        if (!("conversation_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversation_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("first_message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["first_message"] = "";
        }
        if (!("message_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["message_count"] = 0;
        }
        if (!("last_used_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_used_time"] = "";
        }
        if (!("is_generating" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_generating"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalConversation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalConversation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalConversation(/** @type {Partial<LocalConversation>} */($$parsedSource));
    }
}

export class LocalMessage {
    /**
     * Creates a new LocalMessage instance.
     * @param {Partial<LocalMessage>} [$$source = {}] - The source object to create the LocalMessage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("conversation_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversation_id"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalMessage(/** @type {Partial<LocalMessage>} */($$parsedSource));
    }
}

export class UpdateCheckResult {
    /**
     * Creates a new UpdateCheckResult instance.
     * @param {Partial<UpdateCheckResult>} [$$source = {}] - The source object to create the UpdateCheckResult.
     */
    constructor($$source = {}) {
        if (!("has_update" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_update"] = false;
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest_version"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["notes"] = [];
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateCheckResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField3_0($$parsedSource["notes"]);
        }
        return new UpdateCheckResult(/** @type {Partial<UpdateCheckResult>} */($$parsedSource));
    }
}

export class UsageStatus {
    /**
     * Creates a new UsageStatus instance.
     * @param {Partial<UsageStatus>} [$$source = {}] - The source object to create the UsageStatus.
     */
    constructor($$source = {}) {
        if (!("five_hour" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["five_hour"] = 0;
        }
        if (!("five_hour_reset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["five_hour_reset"] = "";
        }
        if (!("seven_day" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seven_day"] = 0;
        }
        if (!("seven_day_reset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["seven_day_reset"] = "";
        }
        if (!("seven_day_sonnet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seven_day_sonnet"] = 0;
        }
        if (!("seven_day_sonnet_reset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["seven_day_sonnet_reset"] = "";
        }
        if (!("is_blocked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_blocked"] = false;
        }
        if (!("block_reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["block_reason"] = "";
        }
        if (!("block_reset_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["block_reset_time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageStatus(/** @type {Partial<UsageStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
