CREATE TABLE public.cld_conversation (
	id bigserial NOT NULL,
	uid varchar NOT NULL,
	device_id int8 NOT NULL,
	CONSTRAINT cld_conversation_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_cld_conversation_device_id ON public.cld_conversation USING btree (device_id);
CREATE UNIQUE INDEX idx_cld_conversation_uid ON public.cld_conversation USING btree (uid);

CREATE TABLE public.cld_device (
	id bigserial NOT NULL,
	platform varchar NOT NULL,
	create_time timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	update_time timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"notice" varchar NULL,
	banned bool DEFAULT false NOT NULL,
	ban_reason varchar NULL,
	"admin" bool DEFAULT false NOT NULL,
	admin_password varchar NOT NULL,
	fingerprint varchar NOT NULL,
	CONSTRAINT cld_device_check CHECK (((platform)::text = ANY ((ARRAY['windows'::character varying, 'android'::character varying, 'linux'::character varying, 'macos'::character varying, 'ios'::character varying])::text[]))),
	CONSTRAINT cld_device_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_cld_device_admin_password ON public.cld_device USING btree (admin_password);
CREATE UNIQUE INDEX idx_cld_device_fingerprint ON public.cld_device USING btree (fingerprint);

CREATE TABLE public.cld_dialogue (
	id bigserial NOT NULL,
	uid varchar NOT NULL,
	conversation_id int8 NOT NULL,
	"order" int8 DEFAULT 1 NOT NULL,
	user_message text NOT NULL,
	assistant_message text NULL,
	create_time timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	finish_time timestamptz NULL,
	request_time timetz NULL,
	status varchar DEFAULT 'processing'::character varying NOT NULL,
	duration int8 NULL,
	CONSTRAINT cld_dialogue_check CHECK (((status)::text = ANY ((ARRAY['waiting'::character varying, 'processing'::character varying, 'replying'::character varying, 'done'::character varying, 'send_failed'::character varying, 'reply_failed'::character varying])::text[]))),
	CONSTRAINT cld_dialogue_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_cld_dialogue_conversation_id ON public.cld_dialogue USING btree (conversation_id);
CREATE INDEX idx_cld_dialogue_create_time ON public.cld_dialogue USING btree (create_time DESC);
CREATE INDEX idx_cld_dialogue_status ON public.cld_dialogue USING btree (status);
CREATE UNIQUE INDEX idx_cld_dialogue_uid ON public.cld_dialogue USING btree (uid);

CREATE TABLE public.cld_error (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	dialogue_id int4 NOT NULL,
	"error" text NOT NULL,
	create_time timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT cld_error_pk PRIMARY KEY (id)
);